import { YarnProduct } from '../types';

export const products: YarnProduct[] = [
  // --- LACE (2) ---
  {
    id: 'p01',
    slug: 'hazel-knits-artisan-lace',
    name: 'Artisan Lace',
    brand: 'Hazel Knits',
    weight: 'lace',
    gauge: { stitches: 30, rows: 42, needleSize: '2.0mm' },
    composition: ['75% merino', '25% nylon'],
    yardage: 400,
    weightGrams: 100,
    price: 129,
    colors: [
      { id: 'c01a', name: 'Fog', hex: '#B8BEC7', inStock: true },
      { id: 'c01b', name: 'Dusty Rose', hex: '#D9A8A0', inStock: true },
      { id: 'c01c', name: 'Evergreen', hex: '#3A5C4E', inStock: false },
      { id: 'c01d', name: 'Birch', hex: '#E8DFD0', inStock: true },
    ],
    description: 'Delikatna włóczka koronkowa z mieszanki merino i nylonu. Idealna do wyszukanych chust, koronkowych sweterków i delikatnych akcesoriów. Wyjątkowa miękkość i połysk.',
    images: ['https://images.unsplash.com/photo-1573515823142-bcf3395c2fec?w=600&h=800&fit=crop&q=80'],
    tags: ['lace', 'merino', 'chusta', 'koronka'],
    rating: 4.8,
    reviewCount: 47,
    isNew: false,
    isBestseller: true,
    projectTypes: ['szal', 'akcesoria'],
    careInstructions: ['Pranie ręczne w zimnej wodzie', 'Suszenie poziome', 'Nie wyżymać'],
  },
  {
    id: 'p02',
    slug: 'malabrigo-lace',
    name: 'Lace',
    brand: 'Malabrigo',
    weight: 'lace',
    gauge: { stitches: 28, rows: 38, needleSize: '2.25mm' },
    composition: ['100% merino'],
    yardage: 470,
    weightGrams: 100,
    price: 149,
    colors: [
      { id: 'c02a', name: 'Zarzamora', hex: '#4A2040', inStock: true },
      { id: 'c02b', name: 'Sunset', hex: '#D4703F', inStock: true },
      { id: 'c02c', name: 'Teal Feather', hex: '#3D8B8B', inStock: true },
      { id: 'c02d', name: 'Natural', hex: '#F0EAD6', inStock: false },
      { id: 'c02e', name: 'Primavera', hex: '#C8B4D0', inStock: true },
    ],
    description: 'Ręcznie farbowana włóczka koronkowa z czystego merino od urugwajskiej marki Malabrigo. Niepowtarzalne efekty barwienia, niezrównana miękkość. Każda motek to unikat.',
    images: ['https://images.unsplash.com/photo-1673696267683-90e6b4bcb24d?w=600&h=800&fit=crop&q=80'],
    tags: ['lace', 'merino', 'hand-dyed', 'premium'],
    rating: 4.9,
    reviewCount: 83,
    isNew: false,
    isBestseller: true,
    projectTypes: ['szal', 'akcesoria'],
    careInstructions: ['Pranie ręczne', 'Zimna woda', 'Suszenie w cieniu'],
  },

  // --- FINGERING (4) ---
  {
    id: 'p03',
    slug: 'drops-fabel',
    name: 'Fabel',
    brand: 'Drops',
    weight: 'fingering',
    gauge: { stitches: 32, rows: 44, needleSize: '2.5mm' },
    composition: ['75% wełna', '25% nylon'],
    yardage: 205,
    weightGrams: 50,
    price: 32,
    colors: [
      { id: 'c03a', name: 'Natural', hex: '#F2ECD8', inStock: true },
      { id: 'c03b', name: 'Camel', hex: '#C19A6B', inStock: true },
      { id: 'c03c', name: 'Denim', hex: '#5B7A9D', inStock: true },
      { id: 'c03d', name: 'Dark Navy', hex: '#1C2B4A', inStock: false },
      { id: 'c03e', name: 'Red', hex: '#B03030', inStock: true },
    ],
    description: 'Klasyczna włóczka skarpetowa od Drops. Trwała mieszanka wełny i nylonu zapewnia długowieczność i odporność na ścieranie. Świetna do skarpet, rękawiczek i drobnych akcesoriów.',
    images: ['https://images.unsplash.com/photo-1645550294607-c9955e906ba2?w=600&h=800&fit=crop&q=80'],
    tags: ['fingering', 'skarpety', 'wełna', 'nylon'],
    rating: 4.5,
    reviewCount: 124,
    isNew: false,
    isBestseller: true,
    projectTypes: ['skarpety', 'akcesoria'],
    careInstructions: ['Pranie maszynowe 40°C', 'Program delikatny', 'Suszenie poziome'],
  },
  {
    id: 'p04',
    slug: 'drops-lima',
    name: 'Lima',
    brand: 'Drops',
    weight: 'fingering',
    gauge: { stitches: 34, rows: 46, needleSize: '2.5mm' },
    composition: ['65% alpaka', '35% wełna'],
    yardage: 175,
    weightGrams: 50,
    price: 45,
    colors: [
      { id: 'c04a', name: 'Off White', hex: '#F5F0E8', inStock: true },
      { id: 'c04b', name: 'Light Beige', hex: '#D4C4A8', inStock: true },
      { id: 'c04c', name: 'Dusty Teal', hex: '#6B9B8E', inStock: true },
      { id: 'c04d', name: 'Charcoal', hex: '#3C3835', inStock: true },
    ],
    description: 'Luksusowa mieszanka alpaki i wełny w cienkim przędziwie. Wyjątkowo miękka w dotyku, z charakterystycznym halo alpakowym. Idealna do delikatnych sweterków i szali.',
    images: ['https://plus.unsplash.com/premium_photo-1675799887840-98178eff888d?w=600&h=800&fit=crop&q=80'],
    tags: ['fingering', 'alpaka', 'luksusowa'],
    rating: 4.7,
    reviewCount: 56,
    isNew: true,
    isBestseller: false,
    projectTypes: ['sweter', 'szal', 'akcesoria'],
    careInstructions: ['Pranie ręczne', 'Letnia woda', 'Suszenie poziome'],
  },
  {
    id: 'p05',
    slug: 'lang-yarns-jawoll',
    name: 'Jawoll',
    brand: 'Lang Yarns',
    weight: 'fingering',
    gauge: { stitches: 32, rows: 44, needleSize: '2.5mm' },
    composition: ['75% wełna superwash', '25% nylon'],
    yardage: 210,
    weightGrams: 50,
    price: 38,
    colors: [
      { id: 'c05a', name: 'Stone', hex: '#9B9089', inStock: true },
      { id: 'c05b', name: 'Forest Green', hex: '#2D4A3E', inStock: true },
      { id: 'c05c', name: 'Terracotta', hex: '#B85C38', inStock: true },
      { id: 'c05d', name: 'Ink Blue', hex: '#2C3D5C', inStock: false },
      { id: 'c05e', name: 'Lemon', hex: '#E8D87A', inStock: true },
    ],
    description: 'Kultowa szwajcarska włóczka skarpetowa z wełny superwash. Łatwa w pielęgnacji, odporna na pranie maszynowe. Ulubieniec dziergaczy skarpet na całym świecie.',
    images: ['https://images.unsplash.com/photo-1773747688454-61ad512ffd5b?w=600&h=800&fit=crop&q=80'],
    tags: ['fingering', 'superwash', 'skarpety', 'szwajcaria'],
    rating: 4.6,
    reviewCount: 98,
    isNew: false,
    isBestseller: false,
    projectTypes: ['skarpety', 'akcesoria'],
    careInstructions: ['Pranie maszynowe 40°C', 'Program wełna'],
  },
  {
    id: 'p06',
    slug: 'lang-yarns-merino-120',
    name: 'Merino 120',
    brand: 'Lang Yarns',
    weight: 'fingering',
    gauge: { stitches: 33, rows: 45, needleSize: '2.5-3.0mm' },
    composition: ['100% merino superwash'],
    yardage: 120,
    weightGrams: 25,
    price: 29,
    colors: [
      { id: 'c06a', name: 'Cream', hex: '#F4EFE6', inStock: true },
      { id: 'c06b', name: 'Powder Pink', hex: '#EECFCA', inStock: true },
      { id: 'c06c', name: 'Sage', hex: '#7A9E8E', inStock: true },
      { id: 'c06d', name: 'Slate', hex: '#7A8B9A', inStock: true },
      { id: 'c06e', name: 'Aubergine', hex: '#5C3060', inStock: false },
      { id: 'c06f', name: 'Mustard', hex: '#C8922A', inStock: true },
    ],
    description: 'Merino superwash najwyższej jakości w cienkim przędziwie. Idealne do niemowlęcych ubranek, delikatnych sweterków i skomplikowanych wzorów koronkowych.',
    images: ['https://images.unsplash.com/photo-1645550294607-c9955e906ba2?w=600&h=800&fit=crop&q=80'],
    tags: ['fingering', 'merino', 'superwash', 'niemowlę'],
    rating: 4.8,
    reviewCount: 71,
    isNew: false,
    isBestseller: false,
    projectTypes: ['sweter', 'skarpety', 'akcesoria'],
    careInstructions: ['Pranie maszynowe 30°C', 'Program delikatny'],
  },

  // --- DK (6) ---
  {
    id: 'p07',
    slug: 'istex-lettlopi',
    name: 'Léttlopi',
    brand: 'Istex',
    weight: 'dk',
    gauge: { stitches: 22, rows: 30, needleSize: '3.5mm' },
    composition: ['100% wełna islandzka'],
    yardage: 100,
    weightGrams: 50,
    price: 48,
    colors: [
      { id: 'c07a', name: 'White', hex: '#F8F4EE', inStock: true },
      { id: 'c07b', name: 'Ash', hex: '#B5AFA8', inStock: true },
      { id: 'c07c', name: 'Black Sheep', hex: '#2A2724', inStock: true },
      { id: 'c07d', name: 'Almond', hex: '#C8A87A', inStock: false },
      { id: 'c07e', name: 'Pine', hex: '#3A5C4E', inStock: true },
    ],
    description: 'Autentyczna islandzka włóczka z wełny owiec rasy islandzkiej. Lekka, ciepła i wodoodporna — stworzona do lopapeysy i nordyckich wzorów. Surowa i charakterystyczna faktura.',
    images: ['https://images.unsplash.com/photo-1598871956222-26b66d6559fe?w=600&h=800&fit=crop&q=80'],
    tags: ['dk', 'islandia', 'lopapeysa', 'nordycka'],
    rating: 4.7,
    reviewCount: 145,
    isNew: false,
    isBestseller: true,
    projectTypes: ['sweter', 'czapka', 'akcesoria'],
    careInstructions: ['Pranie ręczne', 'Zimna woda', 'Suszenie poziome'],
  },
  {
    id: 'p08',
    slug: 'drops-karisma',
    name: 'Karisma',
    brand: 'Drops',
    weight: 'dk',
    gauge: { stitches: 23, rows: 32, needleSize: '3.5mm' },
    composition: ['100% wełna superwash'],
    yardage: 100,
    weightGrams: 50,
    price: 36,
    colors: [
      { id: 'c08a', name: 'Natural', hex: '#EDE8DC', inStock: true },
      { id: 'c08b', name: 'Camel', hex: '#B8935A', inStock: true },
      { id: 'c08c', name: 'Burgundy', hex: '#7A2030', inStock: true },
      { id: 'c08d', name: 'Peacock Blue', hex: '#3A7A8A', inStock: true },
      { id: 'c08e', name: 'Graphite', hex: '#5A5754', inStock: false },
    ],
    description: 'Wszechstronna włóczka DK z wełny superwash. Łatwa w pielęgnacji, dostępna w szerokiej palecie kolorów. Idealna do swetrów, czapek i drobnych akcesoriów dla całej rodziny.',
    images: ['https://images.unsplash.com/photo-1682954100067-c4356f636c6b?w=600&h=800&fit=crop&q=80'],
    tags: ['dk', 'superwash', 'rodzinna', 'wszechstronna'],
    rating: 4.4,
    reviewCount: 189,
    isNew: false,
    isBestseller: true,
    projectTypes: ['sweter', 'czapka', 'akcesoria'],
    careInstructions: ['Pranie maszynowe 40°C', 'Program wełna'],
  },
  {
    id: 'p09',
    slug: 'bc-garn-semilla',
    name: 'Semilla',
    brand: 'BC Garn',
    weight: 'dk',
    gauge: { stitches: 22, rows: 30, needleSize: '4.0mm' },
    composition: ['100% bawełna organiczna'],
    yardage: 175,
    weightGrams: 50,
    price: 52,
    colors: [
      { id: 'c09a', name: 'Ecru', hex: '#F0E8D4', inStock: true },
      { id: 'c09b', name: 'Sky', hex: '#A8C4D4', inStock: true },
      { id: 'c09c', name: 'Mint', hex: '#A8D4C0', inStock: false },
      { id: 'c09d', name: 'Terracotta', hex: '#B85C38', inStock: true },
      { id: 'c09e', name: 'Slate Blue', hex: '#6B8CA0', inStock: true },
    ],
    description: 'Ekologiczna bawełna certyfikowana GOTS od duńskiej marki BC Garn. Miękka, oddychająca i przyjazna środowisku. Idealna do letnich swetrów, dziecięcych ubranek i domowych akcesoriów.',
    images: ['https://plus.unsplash.com/premium_photo-1675799745773-d00668d9790d?w=600&h=800&fit=crop&q=80'],
    tags: ['dk', 'bawełna', 'organiczna', 'lato', 'eko'],
    rating: 4.6,
    reviewCount: 62,
    isNew: true,
    isBestseller: false,
    projectTypes: ['sweter', 'akcesoria', 'amigurumi'],
    careInstructions: ['Pranie maszynowe 40°C', 'Można prasować w niskiej temperaturze'],
  },
  {
    id: 'p10',
    slug: 'istex-plotulopi',
    name: 'Plötulopi',
    brand: 'Istex',
    weight: 'dk',
    gauge: { stitches: 22, rows: 30, needleSize: '4.0mm' },
    composition: ['100% wełna islandzka unspun'],
    yardage: 300,
    weightGrams: 100,
    price: 68,
    colors: [
      { id: 'c10a', name: 'Oatmeal', hex: '#D8CDB8', inStock: true },
      { id: 'c10b', name: 'Fjord', hex: '#4A6E8A', inStock: true },
      { id: 'c10c', name: 'Lava', hex: '#3A3330', inStock: true },
      { id: 'c10d', name: 'Heather', hex: '#9A7A9A', inStock: false },
    ],
    description: 'Wyjątkowa nieprzędzona (unspun) wełna islandzka. Ultra lekka i niezwykle ciepła. Wymaga delikatnego obchodzenia, daje niepowtarzalne efekty — ulubiona przez koneserów islandzkiego dziergania.',
    images: ['https://images.unsplash.com/photo-1598871956222-26b66d6559fe?w=600&h=800&fit=crop&q=80'],
    tags: ['dk', 'unspun', 'islandia', 'premium'],
    rating: 4.8,
    reviewCount: 38,
    isNew: false,
    isBestseller: false,
    projectTypes: ['sweter', 'czapka'],
    careInstructions: ['Tylko pranie ręczne', 'Bardzo zimna woda', 'Suszenie poziome'],
  },
  {
    id: 'p11',
    slug: 'bc-garn-bio-balance',
    name: 'Bio Balance',
    brand: 'BC Garn',
    weight: 'dk',
    gauge: { stitches: 24, rows: 33, needleSize: '3.5mm' },
    composition: ['55% bawełna organiczna', '45% wełna merino'],
    yardage: 130,
    weightGrams: 50,
    price: 59,
    colors: [
      { id: 'c11a', name: 'Vanilla', hex: '#F0E8CC', inStock: true },
      { id: 'c11b', name: 'Mist', hex: '#C4CED4', inStock: true },
      { id: 'c11c', name: 'Olive', hex: '#7A8A50', inStock: true },
      { id: 'c11d', name: 'Coral', hex: '#D4826A', inStock: true },
      { id: 'c11e', name: 'Midnight', hex: '#1E2840', inStock: false },
    ],
    description: 'Zrównoważona mieszanka bawełny organicznej i merino. Łączy miękkość wełny z oddychalnością bawełny. Doskonała przez cały rok — ani za ciepła, ani za chłodna.',
    images: ['https://images.unsplash.com/photo-1682954100067-c4356f636c6b?w=600&h=800&fit=crop&q=80'],
    tags: ['dk', 'merino', 'bawełna', 'organiczna', 'cztery-pory'],
    rating: 4.5,
    reviewCount: 43,
    isNew: false,
    isBestseller: false,
    projectTypes: ['sweter', 'czapka', 'akcesoria'],
    careInstructions: ['Pranie maszynowe 30°C', 'Program delikatny'],
  },
  {
    id: 'p12',
    slug: 'drops-lima-dk',
    name: 'Lima DK',
    brand: 'Drops',
    weight: 'dk',
    gauge: { stitches: 22, rows: 30, needleSize: '4.0mm' },
    composition: ['65% alpaka', '35% wełna'],
    yardage: 110,
    weightGrams: 50,
    price: 55,
    colors: [
      { id: 'c12a', name: 'Pearl', hex: '#EDE8E0', inStock: true },
      { id: 'c12b', name: 'Warm Sand', hex: '#C8B490', inStock: true },
      { id: 'c12c', name: 'Rust', hex: '#A04828', inStock: true },
      { id: 'c12d', name: 'Forest', hex: '#2D4A3E', inStock: false },
      { id: 'c12e', name: 'Storm', hex: '#5A6870', inStock: true },
    ],
    description: 'Alpaka z wełną w grubości DK — niezwykła miękkość i lekkość. Charakterystyczne halo alpakowe nadaje niepowtarzalny, luksusowy wygląd. Idealna do miękkich swetrów i szali.',
    images: ['https://images.unsplash.com/photo-1651651705570-0a081884ce44?w=600&h=800&fit=crop&q=80'],
    tags: ['dk', 'alpaka', 'luksusowa', 'miękka'],
    rating: 4.7,
    reviewCount: 88,
    isNew: false,
    isBestseller: true,
    projectTypes: ['sweter', 'szal', 'czapka'],
    careInstructions: ['Pranie ręczne', 'Letnia woda', 'Suszenie poziome'],
  },

  // --- WORSTED (5) ---
  {
    id: 'p13',
    slug: 'cascade-220',
    name: '220',
    brand: 'Cascade',
    weight: 'worsted',
    gauge: { stitches: 20, rows: 26, needleSize: '4.5mm' },
    composition: ['100% wełna peruwiańska'],
    yardage: 220,
    weightGrams: 100,
    price: 62,
    colors: [
      { id: 'c13a', name: 'Ecru', hex: '#EDE5D0', inStock: true },
      { id: 'c13b', name: 'Pumpkin Spice', hex: '#C07040', inStock: true },
      { id: 'c13c', name: 'Christmas Green', hex: '#1A5C30', inStock: true },
      { id: 'c13d', name: 'Pacific', hex: '#2C5F7A', inStock: true },
      { id: 'c13e', name: 'Jet', hex: '#1C1C1C', inStock: false },
      { id: 'c13f', name: 'Straw', hex: '#D4B86A', inStock: true },
    ],
    description: 'Kultowa wełna worsted od Cascade Yarns. Czysta wełna peruwiańska o niezawodnej jakości i ogromnej palecie kolorów. Idealny wybór do swetrów, koców i projektów Aran.',
    images: ['https://images.unsplash.com/photo-1668072587859-f0f30c8fa938?w=600&h=800&fit=crop&q=80'],
    tags: ['worsted', 'wełna', 'peruwiańska', 'klasyczna'],
    rating: 4.6,
    reviewCount: 203,
    isNew: false,
    isBestseller: true,
    projectTypes: ['sweter', 'koc', 'czapka', 'akcesoria'],
    careInstructions: ['Pranie ręczne', 'Zimna woda', 'Suszenie poziome'],
  },
  {
    id: 'p14',
    slug: 'rowan-pure-wool',
    name: 'Pure Wool Worsted',
    brand: 'Rowan',
    weight: 'worsted',
    gauge: { stitches: 19, rows: 25, needleSize: '5.0mm' },
    composition: ['100% wełna superwash'],
    yardage: 200,
    weightGrams: 100,
    price: 89,
    colors: [
      { id: 'c14a', name: 'Aran', hex: '#EDE5D8', inStock: true },
      { id: 'c14b', name: 'Cinnamon', hex: '#A06040', inStock: true },
      { id: 'c14c', name: 'Cypress', hex: '#3A5040', inStock: true },
      { id: 'c14d', name: 'Marine', hex: '#284068', inStock: false },
      { id: 'c14e', name: 'Granite', hex: '#6A6460', inStock: true },
    ],
    description: 'Elegancka wełna superwash od legendarnej brytyjskiej marki Rowan. Gładka, twarda i doskonale trzyma kształt. Świetna do klasycznych wzorów kablowych i swetrów Aran.',
    images: ['https://images.unsplash.com/photo-1610383120881-32c3b9db9408?w=600&h=800&fit=crop&q=80'],
    tags: ['worsted', 'superwash', 'british', 'premium', 'aran'],
    rating: 4.7,
    reviewCount: 76,
    isNew: false,
    isBestseller: false,
    projectTypes: ['sweter', 'czapka', 'akcesoria'],
    careInstructions: ['Pranie maszynowe 40°C', 'Program wełna'],
  },
  {
    id: 'p15',
    slug: 'schoppel-zauberball',
    name: 'Zauberball',
    brand: 'Schoppel',
    weight: 'worsted',
    gauge: { stitches: 18, rows: 24, needleSize: '5.0mm' },
    composition: ['75% wełna superwash', '25% nylon'],
    yardage: 420,
    weightGrams: 100,
    price: 79,
    colors: [
      { id: 'c15a', name: 'Forest Walk', hex: '#4A7060', inStock: true },
      { id: 'c15b', name: 'Autumn Leaves', hex: '#C07840', inStock: true },
      { id: 'c15c', name: 'Ocean Breeze', hex: '#4A6E8A', inStock: true },
      { id: 'c15d', name: 'Lavender Fields', hex: '#8A78A8', inStock: true },
    ],
    description: 'Magiczna stopniowo zmieniająca kolor włóczka z Niemiec. Samodzielnie tworzy efekt kolorystyczny podczas dziergania. Idealna do szali, skarpet i ciekawych projektów jednokolorowych.',
    images: ['https://plus.unsplash.com/premium_photo-1675799551089-d264f8f2900b?w=600&h=800&fit=crop&q=80'],
    tags: ['worsted', 'gradient', 'kolorowa', 'selbststreifend'],
    rating: 4.8,
    reviewCount: 134,
    isNew: false,
    isBestseller: true,
    projectTypes: ['szal', 'skarpety', 'sweter'],
    careInstructions: ['Pranie maszynowe 40°C', 'Program delikatny'],
  },
  {
    id: 'p16',
    slug: 'cascade-superwash',
    name: 'Cascade 220 Superwash',
    brand: 'Cascade',
    weight: 'worsted',
    gauge: { stitches: 20, rows: 26, needleSize: '4.5mm' },
    composition: ['100% wełna superwash'],
    yardage: 220,
    weightGrams: 100,
    price: 68,
    colors: [
      { id: 'c16a', name: 'White', hex: '#F8F4F0', inStock: true },
      { id: 'c16b', name: 'Lemon Drop', hex: '#E8D860', inStock: true },
      { id: 'c16c', name: 'Bluebell', hex: '#7090C0', inStock: false },
      { id: 'c16d', name: 'Hibiscus', hex: '#C04060', inStock: true },
      { id: 'c16e', name: 'Charcoal', hex: '#3C3C3C', inStock: true },
    ],
    description: 'Wersja superwash popularnej włóczki Cascade 220. Łatwa w pielęgnacji, idealna do projektów dla dzieci i aktywnych użytkowników. Ten sam doskonały skręt, bez konieczności prania ręcznego.',
    images: ['https://images.unsplash.com/photo-1668072587859-f0f30c8fa938?w=600&h=800&fit=crop&q=80'],
    tags: ['worsted', 'superwash', 'dzieci', 'praktyczna'],
    rating: 4.5,
    reviewCount: 167,
    isNew: false,
    isBestseller: false,
    projectTypes: ['sweter', 'czapka', 'koc'],
    careInstructions: ['Pranie maszynowe 40°C', 'Program wełna'],
  },
  {
    id: 'p17',
    slug: 'rowan-felted-tweed',
    name: 'Felted Tweed',
    brand: 'Rowan',
    weight: 'worsted',
    gauge: { stitches: 18, rows: 23, needleSize: '5.0-5.5mm' },
    composition: ['50% merino', '25% alpaka', '25% wiskoza'],
    yardage: 175,
    weightGrams: 50,
    price: 78,
    colors: [
      { id: 'c17a', name: 'Carbon', hex: '#3C3830', inStock: true },
      { id: 'c17b', name: 'Peony', hex: '#C06070', inStock: true },
      { id: 'c17c', name: 'Clay', hex: '#A07860', inStock: true },
      { id: 'c17d', name: 'Teal', hex: '#306870', inStock: false },
      { id: 'c17e', name: 'Camel', hex: '#C8A868', inStock: true },
    ],
    description: 'Ikoniczna tweedowa włóczka Rowan z mieszanki merino, alpaki i wiskozy. Charakterystyczna faktura tweeda z subtelnym połyskiem. Ulubiona do eleganckich swetrów i okryć wierzchnich.',
    images: ['https://images.unsplash.com/photo-1674069686850-e350be379976?w=600&h=800&fit=crop&q=80'],
    tags: ['worsted', 'tweed', 'merino', 'alpaka', 'premium'],
    rating: 4.9,
    reviewCount: 91,
    isNew: false,
    isBestseller: true,
    projectTypes: ['sweter', 'akcesoria', 'szal'],
    careInstructions: ['Pranie ręczne', 'Zimna woda', 'Suszenie poziome'],
  },

  // --- BULKY (3) ---
  {
    id: 'p18',
    slug: 'drops-andes',
    name: 'Andes',
    brand: 'Drops',
    weight: 'bulky',
    gauge: { stitches: 13, rows: 18, needleSize: '6.0mm' },
    composition: ['65% wełna', '35% alpaka'],
    yardage: 100,
    weightGrams: 100,
    price: 55,
    colors: [
      { id: 'c18a', name: 'Off White', hex: '#F0EAE0', inStock: true },
      { id: 'c18b', name: 'Caramel', hex: '#B88A50', inStock: true },
      { id: 'c18c', name: 'Dark Brown', hex: '#4A3828', inStock: true },
      { id: 'c18d', name: 'Petrol', hex: '#2C5868', inStock: false },
      { id: 'c18e', name: 'Charcoal', hex: '#3A3835', inStock: true },
    ],
    description: 'Gruba mieszanka wełny i alpaki od Drops. Szybkie dzierganie i ciepłe rezultaty. Idealna do zimowych swetrów, koców i ciepłych czapek na mroźne dni.',
    images: ['https://images.unsplash.com/photo-1651651705570-0a081884ce44?w=600&h=800&fit=crop&q=80'],
    tags: ['bulky', 'alpaka', 'wełna', 'szybkie-dzierganie'],
    rating: 4.6,
    reviewCount: 112,
    isNew: false,
    isBestseller: true,
    projectTypes: ['sweter', 'koc', 'czapka'],
    careInstructions: ['Pranie ręczne', 'Zimna woda', 'Suszenie poziome'],
  },
  {
    id: 'p19',
    slug: 'drops-eskimo',
    name: 'Eskimo',
    brand: 'Drops',
    weight: 'bulky',
    gauge: { stitches: 14, rows: 20, needleSize: '6.0mm' },
    composition: ['100% wełna'],
    yardage: 50,
    weightGrams: 50,
    price: 28,
    colors: [
      { id: 'c19a', name: 'Natural White', hex: '#F4EEE4', inStock: true },
      { id: 'c19b', name: 'Red', hex: '#A83030', inStock: true },
      { id: 'c19c', name: 'Navy', hex: '#1C2B4A', inStock: true },
      { id: 'c19d', name: 'Grey', hex: '#8A8784', inStock: true },
    ],
    description: 'Klasyczna gruba wełna o miękkiej, puszystej fakturze. Łatwa w obsłudze, idealna dla początkujących. Świetna do projektów w ramach jednego wieczoru — czapki, szaliki, rękawiczki.',
    images: ['https://plus.unsplash.com/premium_photo-1674624789813-aee3aaa976cb?w=600&h=800&fit=crop&q=80'],
    tags: ['bulky', 'wełna', 'początkujący', 'szybkie'],
    rating: 4.3,
    reviewCount: 78,
    isNew: false,
    isBestseller: false,
    projectTypes: ['czapka', 'szal', 'akcesoria'],
    careInstructions: ['Pranie ręczne', 'Zimna woda'],
  },
  {
    id: 'p20',
    slug: 'katia-concept-soft-merino',
    name: 'Concept Soft Merino',
    brand: 'Katia',
    weight: 'bulky',
    gauge: { stitches: 12, rows: 16, needleSize: '7.0mm' },
    composition: ['100% merino superwash'],
    yardage: 80,
    weightGrams: 100,
    price: 85,
    colors: [
      { id: 'c20a', name: 'Cream', hex: '#F4EFE6', inStock: true },
      { id: 'c20b', name: 'Blush', hex: '#E0B0A8', inStock: true },
      { id: 'c20c', name: 'Sage', hex: '#7A9E8E', inStock: true },
      { id: 'c20d', name: 'Denim', hex: '#4A6880', inStock: false },
      { id: 'c20e', name: 'Warm Brown', hex: '#8A6040', inStock: true },
      { id: 'c20f', name: 'Slate', hex: '#6A7078', inStock: true },
    ],
    description: 'Luksusowe grube merino superwash od Katia. Niesamowicie miękkie w dotyku, easy-care i niezwykle efektowne. Idealne do oversizowych swetrów i koców o eleganckiej, nowoczesnej estetyce.',
    images: ['https://images.unsplash.com/photo-1668072587819-7b393944b426?w=600&h=800&fit=crop&q=80'],
    tags: ['bulky', 'merino', 'luksusowa', 'superwash', 'oversized'],
    rating: 4.8,
    reviewCount: 55,
    isNew: true,
    isBestseller: false,
    projectTypes: ['sweter', 'koc', 'czapka'],
    careInstructions: ['Pranie maszynowe 30°C', 'Program delikatny', 'Suszenie poziome'],
  },
];
